name: Depoy Nodejs app to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Via SSH
        uses: appleboy/ssh-actions@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: winter
          key: ${{ secrets.SSH_KEY }}
          scripts: |
            cd /home/winter/node-github-actions
            git pull
            docker-compose up -d --build
